[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_FLAGS = "--version"

# Force npm instead of pnpm
[build.processing]
  skip_processing = false

# Override auto-detection
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true